"""
app/vision/multimodal_types.py - Multimodal Pipeline Enums
=========================================================
Defines standard enums for context sources, image roles, vision confidence levels,
prompt section ordering, reasoning modes, and response presentation modes.
"""

from enum import Enum


class ContextSource(str, Enum):
    """Source component feeding into the unified ChatML prompt."""
    SYSTEM = "system"
    MEMORY = "memory"
    EMOTION = "emotion"
    RAG = "rag"
    TOOL = "tool"
    VISION = "vision"
    OCR = "ocr"
    ANALYSIS = "analysis"
    USER = "user"
    HISTORY = "history"


class ImageRole(str, Enum):
    """Role of uploaded image within user query context."""
    PRIMARY_SUBJECT = "primary_subject"
    SUPPORTING_DOCUMENT = "supporting_document"
    CODE_SNIPPET = "code_snippet"
    ERROR_TRACE = "error_trace"
    UI_LAYOUT = "ui_layout"
    REFERENCE = "reference"
    BACKGROUND = "background"


class VisionConfidence(str, Enum):
    """Confidence level assigned to visual analysis."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNCERTAIN = "uncertain"


class PromptSection(str, Enum):
    """Prompt section assembly order."""
    SYSTEM_PERSONA = "system_persona"
    MEMORY_SECTION = "memory_section"
    EMOTION_SECTION = "emotion_section"
    RAG_SECTION = "rag_section"
    TOOL_SECTION = "tool_section"
    VISION_SECTION = "vision_section"
    HISTORY_SECTION = "history_section"
    USER_SECTION = "user_section"


class ReasoningMode(str, Enum):
    """Unified pipeline reasoning execution mode."""
    TEXT_ONLY = "text_only"
    MULTIMODAL = "multimodal"
    TOOL_AUGMENTED = "tool_augmented"
    RAG_AUGMENTED = "rag_augmented"
    FULL_HYBRID = "full_hybrid"


class ResponseMode(str, Enum):
    """Output presentation mode generated by LLM Generator."""
    DIRECT_ANSWER = "direct_answer"
    STEP_BY_STEP_ANALYSIS = "step_by_step_analysis"
    CODE_EXPLANATION = "code_explanation"
    BUG_FIX_SUGGESTION = "bug_fix_suggestion"
    UI_UX_AUDIT = "ui_ux_audit"
