r"""
app/vision/vision_schemas.py - Data Models for Vision AI Subsystem
==================================================================
Defines strongly-typed dataclasses for image metadata, vision requests,
OCR results, captioning results, visual analysis, image context blocks, and vision results.
"""

import time
import uuid
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from app.vision.vision_types import ImageFormat, ImageType, VisionTask, OCRStatus, VisionStatus, AnalysisMode


@dataclass
class ImageMetadata:
    """Detailed structural and technical metadata extracted from an image file."""
    image_id: str = field(default_factory=lambda: f"img_{uuid.uuid4().hex[:12]}")
    file_path: str = ""
    file_name: str = ""
    file_size_bytes: int = 0
    format: ImageFormat = ImageFormat.UNKNOWN
    width: int = 0
    height: int = 0
    aspect_ratio: float = 0.0
    sha256_hash: str = ""
    source: str = "telegram_upload"


@dataclass
class CaptionResult:
    """Outputs generated by vision image captioning models."""
    short_caption: str = ""
    detailed_caption: str = ""
    confidence: float = 0.0


@dataclass
class OCRResult:
    """Outputs produced by Optical Character Recognition text extraction engine."""
    status: OCRStatus = OCRStatus.IDLE
    raw_text: str = ""
    detected_languages: List[str] = field(default_factory=lambda: ["en"])
    line_count: int = 0
    word_count: int = 0
    confidence: float = 0.0
    bounding_boxes: List[Dict[str, Any]] = field(default_factory=list)
    error_message: Optional[str] = None


@dataclass
class ImageAnalysis:
    """High-level visual analysis features extracted from the image."""
    detected_objects: List[str] = field(default_factory=list)
    scene_type: str = "unknown"
    ui_elements: List[str] = field(default_factory=list)
    code_snippets: List[str] = field(default_factory=list)
    summary: str = ""


@dataclass
class VisionRequest:
    """Incoming request instructing VisionManager to process an image."""
    image_path: str
    user_id: str = "default_user"
    conversation_id: str = "default_session"
    request_id: str = field(default_factory=lambda: f"vreq_{uuid.uuid4().hex[:12]}")
    tasks: List[VisionTask] = field(default_factory=lambda: [VisionTask.CAPTIONING, VisionTask.OCR])
    analysis_mode: AnalysisMode = AnalysisMode.BALANCED
    user_prompt: Optional[str] = None
    timestamp: float = field(default_factory=time.time)


@dataclass
class ImageContext:
    """Structured context payload generated by VisionManager for PromptBuilder context injection."""
    request_id: str = ""
    metadata: ImageMetadata = field(default_factory=ImageMetadata)
    image_type: ImageType = ImageType.UNKNOWN
    caption_result: CaptionResult = field(default_factory=CaptionResult)
    ocr_result: OCRResult = field(default_factory=OCRResult)
    analysis: ImageAnalysis = field(default_factory=ImageAnalysis)
    formatted_prompt_block: str = ""
    processing_time_ms: float = 0.0


@dataclass
class VisionResult:
    """Standardized result returned by VisionManager to callers or pipelines."""
    result_id: str = field(default_factory=lambda: f"vres_{uuid.uuid4().hex[:12]}")
    request_id: str = ""
    status: VisionStatus = VisionStatus.PENDING
    image_context: Optional[ImageContext] = None
    error_message: Optional[str] = None
    raw_exception: Optional[Exception] = None
