"""
app/vision/vision_models/vision_schemas.py - Vision Model & Inference Data Schemas
=================================================================================
Defines strongly-typed dataclasses for captions, object detection bounding boxes,
OCR text results, visual contexts, requests, responses, and execution statistics.
"""

import time
import uuid
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, field
from app.vision.vision_models.vision_types import VisionTask, VisionStatus, DetectionType


@dataclass
class CaptionResult:
    """Multimodal scene descriptions generated by Florence-2."""
    short_caption: str = ""
    detailed_caption: str = ""
    dense_captions: List[Dict[str, Any]] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class ObjectDetectionResult:
    """Bounding box region and spatial label detected in visual scene."""
    label: str = ""
    confidence: float = 0.0
    bbox: Tuple[int, int, int, int] = (0, 0, 0, 0)   # (x1, y1, x2, y2)
    detection_type: DetectionType = DetectionType.BOUNDING_BOX


@dataclass
class OCRTextResult:
    """Text extraction output generated by EasyOCR / Florence-2 OCR."""
    raw_text: str = ""
    line_count: int = 0
    word_count: int = 0
    confidence: float = 0.0
    regions: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class ImageContext:
    """Unified structured understanding context block ready for PromptBuilder."""
    request_id: str = ""
    file_path: str = ""
    caption: CaptionResult = field(default_factory=CaptionResult)
    objects: List[ObjectDetectionResult] = field(default_factory=list)
    ocr: OCRTextResult = field(default_factory=OCRTextResult)
    image_type: str = "unknown"
    formatted_prompt_block: str = ""
    inference_time_ms: float = 0.0


@dataclass
class VisionRequest:
    """Inference request payload targeting VisionModelPipeline."""
    image_path: str
    task: VisionTask = VisionTask.DETAILED_CAPTION
    prompt: Optional[str] = None
    user_id: str = "default_user"
    conversation_id: str = "default_session"
    request_id: str = field(default_factory=lambda: f"vreq_{uuid.uuid4().hex[:12]}")
    timestamp: float = field(default_factory=time.time)


@dataclass
class VisionResponse:
    """Standardized response output from VisionModelPipeline."""
    request_id: str = ""
    status: VisionStatus = VisionStatus.PENDING
    context: Optional[ImageContext] = None
    error_message: Optional[str] = None
    inference_time_ms: float = 0.0


@dataclass
class VisionStatistics:
    """Operational telemetry counters for Vision AI inference calls."""
    total_requests: int = 0
    successful_requests: int = 0
    failed_requests: int = 0
    cache_hits: int = 0
    total_inference_time_ms: float = 0.0
    average_latency_ms: float = 0.0
