"""
app/vision/image_analysis/analysis_models.py - Data Models for Image Analysis
=============================================================================
Defines strongly-typed dataclasses for UI structures, code syntax analysis,
document layouts, chart metrics, analysis requests, results, and context payloads.
"""

import time
import uuid
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field

from app.vision.image_analysis.analysis_types import (
    ImageCategory,
    AnalyzerType,
    ConfidenceLevel,
    ChartType,
    DiagramType,
    CodeLanguage,
    DocumentType
)


@dataclass
class UIStructure:
    """Detailed structural features extracted from UI screenshots."""
    buttons: List[str] = field(default_factory=list)
    menus: List[str] = field(default_factory=list)
    inputs: List[str] = field(default_factory=list)
    cards: List[str] = field(default_factory=list)
    visual_hierarchy: str = ""
    accessibility_warnings: List[str] = field(default_factory=list)


@dataclass
class CodeStructure:
    """Detailed features extracted from IDE / terminal code screenshots."""
    detected_language: CodeLanguage = CodeLanguage.UNKNOWN
    framework: str = ""
    error_type: Optional[str] = None
    stack_trace: Optional[str] = None
    line_numbers: List[int] = field(default_factory=list)
    suggested_fix: Optional[str] = None


@dataclass
class DocumentStructure:
    """Detailed features extracted from research papers, invoices, and assignments."""
    document_type: DocumentType = DocumentType.UNKNOWN
    title: Optional[str] = None
    authors: List[str] = field(default_factory=list)
    abstract: Optional[str] = None
    headings: List[str] = field(default_factory=list)
    sections: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)


@dataclass
class ChartStructure:
    """Detailed metrics extracted from charts, graphs, and plots."""
    chart_type: ChartType = ChartType.UNKNOWN
    x_axis_label: Optional[str] = None
    y_axis_label: Optional[str] = None
    data_trends: List[str] = field(default_factory=list)
    key_insights: List[str] = field(default_factory=list)


@dataclass
class AnalysisRequest:
    """Incoming payload passed to AnalysisManager."""
    image_path: str
    category: Optional[ImageCategory] = None
    caption: str = ""
    ocr_text: str = ""
    objects: List[Any] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    request_id: str = field(default_factory=lambda: f"areq_{uuid.uuid4().hex[:12]}")
    timestamp: float = field(default_factory=time.time)


@dataclass
class AnalysisResult:
    """Domain-specific analysis output generated by specialized analyzer."""
    category: ImageCategory = ImageCategory.UNKNOWN
    confidence: float = 0.0
    analyzer_used: AnalyzerType = AnalyzerType.DEFAULT_ANALYZER
    ui_structure: Optional[UIStructure] = None
    code_structure: Optional[CodeStructure] = None
    document_structure: Optional[DocumentStructure] = None
    chart_structure: Optional[ChartStructure] = None
    domain_summary: str = ""
    execution_time_ms: float = 0.0

    @property
    def summary(self) -> str:
        return self.domain_summary


@dataclass
class AnalysisContext:
    """Structured domain context block ready for PromptBuilder injection."""
    request_id: str = ""
    file_path: str = ""
    category: ImageCategory = ImageCategory.UNKNOWN
    formatted_prompt_block: str = ""
    result: Optional[AnalysisResult] = None
