"""
app/llm/response_formatter.py - Response Cleaning & Telegram Format Adapter
=============================================================================

1. PURPOSE:
-----------
Cleans raw text output generated by the Qwen language model. Removes control tokens,
strips prompt echo artifacts, trims trailing whitespace, and enforces Telegram's 4096-character limit.

2. WHY IT EXISTS:
-----------------
- Raw LLM token outputs often include special stop tags (e.g. `<|im_end|>`, `<|endoftext|>`).
- Models may occasionally echo the original prompt before outputting the answer.
- Telegram's Bot API returns an HTTP 400 error if any message body exceeds 4096 characters.

3. HOW IT COMMUNICATES WITH OTHER FILES:
----------------------------------------
- Called by `app/llm/generator.py` or chat handler after decoding token IDs.

4. EXECUTION FLOW:
------------------
1. Receives raw decoded string.
2. Strips known special tokens and ChatML tags.
3. Removes duplicated prompt text if present.
4. Trims leading/trailing empty lines.
5. Truncates cleanly if string exceeds Telegram max length (4096 chars).

5. COMMON MISTAKES:
-------------------
- Allowing `<|im_end|>` to reach Telegram chat UI.
- Naively cutting text mid-word at character 4096, creating broken code blocks.
"""

import re
import logging
from typing import Optional

logger = logging.getLogger("sana_ai.llm.response_formatter")

MAX_TELEGRAM_MESSAGE_LENGTH = 4000  # Safe threshold below 4096


class ResponseFormatter:
    """
    Cleans, formats, and sanitizes LLM response text for Telegram delivery.
    """

    @staticmethod
    def clean_response(raw_text: str, original_prompt: Optional[str] = None) -> str:
        """
        Cleans special control tokens, prompt echos, and formatting issues.

        Args:
            raw_text (str): Raw string decoded from model generation.
            original_prompt (Optional[str]): Prompt passed to model (used to detect prompt echo).

        Returns:
            str: Cleaned human-readable response string.
        """
        if not raw_text:
            return "I apologize, but I couldn't generate a response. Please try asking again."

        cleaned = raw_text

        # 1. Remove prompt echo if model repeated the input prompt at start of output
        if original_prompt and cleaned.startswith(original_prompt):
            cleaned = cleaned[len(original_prompt):]

        # 2. Remove ChatML / Qwen special control tokens
        special_tokens = [
            "<|im_start|>",
            "<|im_end|>",
            "<|endoftext|>",
            "assistant\n",
            "system\n",
            "user\n"
        ]
        for token in special_tokens:
            cleaned = cleaned.replace(token, "")

        # 3. Clean up leading/trailing whitespace and multiple empty lines
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).strip()

        # 4. Enforce Telegram message length limit (4000 chars safety margin)
        if len(cleaned) > MAX_TELEGRAM_MESSAGE_LENGTH:
            logger.warning(
                f"Response length ({len(cleaned)} chars) exceeds max limit ({MAX_TELEGRAM_MESSAGE_LENGTH}). Truncating safely."
            )
            cleaned = cleaned[:MAX_TELEGRAM_MESSAGE_LENGTH] + "\n\n... *(Response truncated due to length)*"

        # 5. Final empty check fallback
        if not cleaned:
            cleaned = "I generated a response, but it contained no readable text. Please rephrase your question."

        return cleaned
