"""
app/conversation/conversation_manager.py - Central Conversation Manager
========================================================================

1. PURPOSE:
-----------
Acts as the central Singleton orchestrator for the Conversation Management Layer.
Coordinates `SessionManager`, `ConversationHistory`, and `ContextWindow` to manage multi-user
dialog memory across Telegram sessions.

2. WHY IT EXISTS:
-----------------
Provides a unified, simplified public API for Telegram handlers and AI services.
Instead of handlers manually juggling session locks, history lists, and trimming logic,
handlers call high-level methods on `ConversationManager.get_instance()`.

3. RESPONSIBILITIES:
--------------------
- Manage lifecycle of user chat sessions.
- Record incoming user messages and outgoing AI assistant responses per `user_id`.
- Retrieve trimmed, role-formatted conversation histories ready for LLM prompt generation.
- Clear individual user conversation histories via `/clear`.

4. COMMUNICATION WITH OTHER MODULES:
------------------------------------
- Imports `SessionManager` from `app/conversation/session.py`.
- Imports `ContextWindow` from `app/conversation/context_window.py`.
- Called by `bot/handlers/echo.py` (chat message logging) and `bot/handlers/common.py` (`/clear` command).

5. COMPLETE CODE:
-----------------
"""

import logging
import threading
from typing import List, Dict, Optional

from app.conversation.session import SessionManager, Session
from app.conversation.context_window import ContextWindow, DEFAULT_MAX_MESSAGES

logger = logging.getLogger("sana_ai.conversation.manager")


class ConversationManager:
    """
    Thread-safe Singleton orchestrator managing multi-user conversation sessions.
    """
    _instance: Optional["ConversationManager"] = None
    _lock: threading.Lock = threading.Lock()

    def __init__(self, max_messages_per_session: int = DEFAULT_MAX_MESSAGES) -> None:
        """Private constructor enforcing Singleton pattern."""
        if ConversationManager._instance is not None:
            raise RuntimeError(
                "ConversationManager is a Singleton! Use `ConversationManager.get_instance()` instead."
            )
        
        self.session_manager: SessionManager = SessionManager()
        self.context_window: ContextWindow = ContextWindow(max_messages=max_messages_per_session)

    @classmethod
    def get_instance(cls) -> "ConversationManager":
        """
        Thread-safe accessor for the ConversationManager Singleton instance.

        Returns:
            ConversationManager: Shared Singleton instance.
        """
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = cls()
        return cls._instance

    def add_user_message(self, user_id: int, content: str) -> None:
        """
        Records a user message into the specified user's conversation session.

        Args:
            user_id (int): Telegram User ID.
            content (str): Text prompt sent by user.
        """
        session: Session = self.session_manager.get_or_create_session(user_id)
        session.history.add_user_message(content)
        logger.debug(f"Logged User message for User ID {user_id} [Count: {session.history.message_count()}]")

    def add_assistant_message(self, user_id: int, content: str) -> None:
        """
        Records an assistant response into the specified user's conversation session.

        Args:
            user_id (int): Telegram User ID.
            content (str): Response text generated by Qwen.
        """
        session: Session = self.session_manager.get_or_create_session(user_id)
        session.history.add_assistant_message(content)
        logger.debug(f"Logged Assistant response for User ID {user_id} [Count: {session.history.message_count()}]")

    def get_formatted_history(self, user_id: int) -> List[Dict[str, str]]:
        """
        Retrieves trimmed, serialized conversation history for the specified user.

        Args:
            user_id (int): Telegram User ID.

        Returns:
            List[Dict[str, str]]: List of message dictionaries ready for PromptBuilder.
        """
        session: Session = self.session_manager.get_or_create_session(user_id)
        return self.context_window.get_trimmed_history(session.history)

    def clear_user_history(self, user_id: int) -> bool:
        """
        Clears all conversation history for the specified user.

        Args:
            user_id (int): Telegram User ID.

        Returns:
            bool: True if history existed and was cleared, False otherwise.
        """
        logger.info(f"🧹 Clearing conversation history for User ID: {user_id}")
        return self.session_manager.clear_session(user_id)

    def get_user_message_count(self, user_id: int) -> int:
        """
        Returns count of messages stored for the specified user.

        Args:
            user_id (int): Telegram User ID.

        Returns:
            int: Message count.
        """
        session = self.session_manager.get_session(user_id)
        return session.history.message_count() if session else 0
